name: default

on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: ghcr.io

jobs:
  prettier:
    name: prettier --check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actionsx/prettier@v2
        with:
          args: --check api/ client/

  eslint/api:
    name: api/eslint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: "yarn"
          check-latest: true
          cache-dependency-path: api/yarn.lock
      - run: yarn install
        working-directory: api/
      - run: yarn eslint ./
        working-directory: api/

  eslint/client:
    name: client/eslint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: "yarn"
          check-latest: true
          cache-dependency-path: client/yarn.lock
      - run: yarn install
        working-directory: client/
      - run: yarn eslint ./
        working-directory: client/